# Generated by Django 5.1.7 on 2025-04-02 18:28

import development.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название проекта')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('priority', models.CharField(choices=[('high', 'Высокий'), ('medium', 'Средний'), ('low', 'Низкий')], default='medium', max_length=10, verbose_name='Приоритет')),
                ('date_start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата начала')),
                ('date_end', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный проект')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-date_start'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_employment', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата приема')),
                ('date_dismissal', models.DateTimeField(blank=True, null=True, verbose_name='Дата увольнения')),
                ('email', models.EmailField(max_length=254, verbose_name='Контактный email')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Должность')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название фичи')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('planned', 'Запланировано'), ('in_progress', 'В разработке'), ('completed', 'Завершено'), ('postponed', 'Отложено')], default='planned', max_length=20, verbose_name='Статус')),
                ('date_start', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала разработки')),
                ('date_end', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения разработки')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_features', to='development.employee', verbose_name='Создатель')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='development.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Фича',
                'verbose_name_plural': 'Фичи',
                'ordering': ['project', '-date_start'],
            },
        ),
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('UI', 'UI Issue'), ('backend', 'Backend Issue'), ('performance', 'Performance Issue'), ('security', 'Security Vulnerability'), ('database', 'Database Issue')], default='backend', max_length=20, verbose_name='Категория')),
                ('priority', models.CharField(choices=[('critical', 'Критичный'), ('high', 'Высокий'), ('medium', 'Средний'), ('low', 'Низкий')], default='medium', max_length=10, verbose_name='Приоритет')),
                ('reported_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата сообщения')),
                ('deadline', models.DateTimeField(default=development.models.default_deadline, verbose_name='Срок исправления')),
                ('fixed_at', models.DateTimeField(blank=True, null=True, verbose_name='Фактическая дата исправления')),
                ('description', models.TextField(default='No description provided', verbose_name='Описание проблемы')),
                ('steps_to_reproduce', models.TextField(blank=True, verbose_name='Шаги воспроизведения')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bugs', to='development.employee', verbose_name='Назначено')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_bugs', to='development.employee', verbose_name='Кто сообщил')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bugs', to='development.feature', verbose_name='Фича')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bugs', to='development.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Баг',
                'verbose_name_plural': 'Баги',
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('developer', 'Разработчик'), ('tester', 'Тестировщик'), ('manager', 'Менеджер'), ('analyst', 'Аналитик')], default='developer', max_length=10, verbose_name='Роль в проекте')),
                ('date_in', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата включения в проект')),
                ('date_out', models.DateTimeField(blank=True, null=True, verbose_name='Дата выхода из проекта')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='development.project', verbose_name='Проект')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='development.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Участие в проекте',
                'verbose_name_plural': 'Участия в проектах',
                'ordering': ['-date_in'],
                'unique_together': {('user', 'project')},
            },
        ),
    ]
