# Generated by Django 5.1.7 on 2025-04-13 10:28

import development.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0002_alter_employee_options_remove_employee_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='reported_at',
            field=models.DateTimeField(default=development.models.two_days_ago, verbose_name='Дата сообщения'),
        ),
    ]
