# Generated by Django 5.1.7 on 2025-04-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=100)),
                ('non_key_field', models.IntegerField()),
            ],
            options={
                'db_table': 'test_data',
            },
        ),
    ]
